# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff451b72bdcab770e478707d96700af8583a60a06120eb50954ea34badf074b8efeccfa9d61e00cd639b202b6eaf501ccdaef775063c9f20b13046662af540f4

test:
  secret_key_base: 239bdcbe9760e8e6504c679bc2ae8ebea4405a85868aa88da27bdcf0d9e941e6067e3331b2a754c50c9fe5fe7ee3def6727d68ce5d8a68100149bb9fb2a73f84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
